launch:
    parameters:
        logger-num:
            description: Number of loggers
            type: int
            default: 2
    steps:
        - init-consumer:
              action: provisionVms
              parameters:
                  phase: "init-consumer"
                  hardwareId: "m1.small"
                  roleName: consumer
                  vmIdentity: ec2-user
                  imageId: us-east-1/ami-3ecd1e57
              output:
                consumerips: ips

        - init-logger:
              action: provisionVms
              parameters:
                  phase: "init-logger"
                  quantity: "{$.logger-num}"
                  hardwareId: "m1.small"
                  roleName: logger
                  vmIdentity: ec2-user
                  imageId: us-east-1/ami-3ecd1e57
              output:
                loggerips: ips

        - start-consumer:
            action: chefsolo
            parameters:
              phase: "start-consumer"
              roles: [ consumer ]
              precedingPhases: [ init-consumer ]
              recipeUrl: https://dl.dropboxusercontent.com/u/957640/manifest/cookbooks-2.tar.gz
              runList: [ "recipe[logstash]", "recipe[logstash::kibana]" ]
              jattrs:
                logstash:
                  user: ec2-user
                  group: ec2-user
                  
        - start-logger:
            action: chefsolo
            parameters:
              phase: "start-logger"
              roles: [ logger ]
              precedingPhases: [ init-logger, start-consumer ]
              recipeUrl: https://dl.dropboxusercontent.com/u/957640/manifest/nxlog.tar.gz
              runList: [ "recipe[nxlog::logger]" ]
              jattrs:
                nxlog:
                  user: ec2-user
                  group: ec2-user
                  root: /home/ec2-user/nxlog
                  monitor_dir: /home/ec2-user/.undeploy.me
                  consumer: "{$.consumerips[0]}"

        - run-command:
            action: execrun
            parameters:
              phase: "run-command"
              roles: [ logger ]
              precedingPhases: [ start-logger ]
              command:
                - 'echo "Hello from execrun!"'
                  
        - dummy-chefrun:
            action: chefsolo
            parameters:
              phase: "dummy-chefrun"
              roles: [ logger ]
              precedingPhases: [ start-logger ]
              recipeUrl: https://dl.dropboxusercontent.com/u/957640/manifest/nxlog.tar.gz
              runList: [ "recipe[nxlog]" ]
              jattrs:
                nxlog:
                  user: ec2-user
                  group: ec2-user
                  root: /home/ec2-user/nxlog
    return:
        consumer:
            description: Consumer 
            value: "{$.consumerips[0]}"
        kibana:
            description: Kibana UI 
            value: "http://{$.consumerips[0]}/kibana-master/src/index.html#/dashboard/file/logstash.json"
        logger:
            description: Logger
            value: "{$.loggerips}"
 
destroy:
        steps:
        - destroy-vm:
            action: undeployEnv
            parameters:
                phase: destroy