default['nxlog']['user'] = 'nxlog'
default['nxlog']['group'] = 'nxlog'
default['nxlog']['root'] = '/var/lib/nxlog'
default['nxlog']['monitor_dir'] = '/var/log'
default['nxlog']['consumer'] = 'localhost'
